name: Show Pods

on:
  workflow_dispatch:

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.K8S_MONITOR_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          echo "K3S:"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa k8s-monitor@192.168.208.3 "kubectl get pods -A"
          
          echo ""
          echo "K8S:"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa k8s-monitor@192.168.203.2 "kubectl get pods -A"